# docker-compose.yml (BASE - COMMON)
version: '3.8'

services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:7.5.0'
    hostname: zookeeper
    container_name: zookeeper-seoul-flow
    networks:
      - seoul-flow-net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: 'confluentinc/cp-kafka:7.5.0'
    hostname: kafka
    container_name: kafka-seoul-flow
    depends_on:
      - zookeeper
    networks:
      - seoul-flow-net
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  akhq:
    image: 'tchiotludo/akhq'
    container_name: akhq-seoul-flow
    depends_on:
      - kafka
    networks:
      - seoul-flow-net

networks:
  seoul-flow-net:
    driver: bridge