# docker-compose.dev.yml (FOR LOCAL DEVELOPMENT)
version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: seoul-flow-frontend-dev
    ports:
      - "${FE_PORT}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - seoul-flow-net

  zookeeper:
    ports:
      - "${ZOOKEEPER_PORT}:2181"

  kafka:
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:${KAFKA_PORT}

  akhq:
    ports:
      - "${AKHQ_PORT}:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-cluster:
              properties:
                bootstrap.servers: "kafka:29092"