# 빌드 스테이지
FROM gradle:8.5.0-jdk17 AS build
WORKDIR /app
COPY . .
RUN gradle build -x test

# 실행 스테이지
FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/build/libs/*.jar /app/seoul-flow.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/seoul-flow.jar"]
